site_name: 'Leonardo Services Documentation'
docs_dir: '../../docs/en'                           # Where to find the markdown files
site_dir: '../../generated/en'                           # Where to put the HTML files

theme:
    name: material
    custom_dir: '../../overrides/'                   # This is where the customization of the theme lives
    logo: assets/images/logo.png                     # The logo is shared by all languages
    favicon: assets/images/favicon.ico               # The favicon is shared by all languages
    language: en                    # The build's language
    features:
    - navigation.top
    - search.highlight
    - search.suggest
extra_css:
  - assets/stylesheets/eng-standard-theme.css                   # CSS is shared by all languages
  - assets/stylesheets/fabric.min.css
  - assets/stylesheets/table.css                   # CSS is shared by all languages 
  - assets/stylesheets/toc.css 
  - assets/stylesheets/language-switcher.css                    # Language switcher styles

extra_javascript:
  - assets/js/toc.js  
  - assets/js/language-switcher.js                              # Language switcher functionality

plugins:
  - search:
      lang: en                       # Set language for search
  - render_swagger:
      css: swagger-ui.css           # Correctly indented plugin config
  - print-site:
      add_to_navigation: false
      print_page_title: 'Stampa'
      add_table_of_contents: false
      toc_title: 'Indice dei contenuti'
      toc_depth: 6
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true

nav:
- Services Overview: index.md
- Infrastructure as a Service (IaaS) Category: IaaS.md
- Container as a Service (CaaS) Category: CaaS.md
- Platform as a Service (PaaS) Category: PaaS.md
- Hybrid Edge Category: Hybrid.md
- Price List: Price.md
- Service Provisioning: Provisioning.md
- Service Management: ITSM.md
- Test Account Management: Test.md
- Data Center Description: DC.md
- Service Level Agreement (SLA): SLA.md

markdown_extensions:
  - markdown_captions
  - admonition
  - pymdownx.details
  - pymdownx.superfences