site_name: 'Leonardo Services Documentation'
docs_dir: '../../docs/it'                           # Where to find the markdown files
site_dir: '../../generated/it'                           # Where to put the HTML files

theme:
    name: material
    custom_dir: '../../overrides/'                   # This is where the customization of the theme lives
    logo: assets/images/logo.png                     # The logo is shared by all languages
    favicon: assets/images/favicon.ico               # The favicon is shared by all languages
    language: it                    # The build's language
    features:
    - navigation.top
    - search.highlight
    - search.suggest
extra_css:
  - assets/stylesheets/eng-standard-theme.css                   # CSS is shared by all languages
  - assets/stylesheets/fabric.min.css
  - assets/stylesheets/table.css                   # CSS is shared by all languages 
  - assets/stylesheets/toc.css 
  - assets/stylesheets/language-switcher.css                    # Language switcher styles

extra_javascript:
  - assets/js/toc.js  
  - assets/js/language-switcher.js                              # Language switcher functionality

plugins:
  - search:
      lang: it                       # Set language for search
  - render_swagger:
      css: swagger-ui.css           # Correctly indented plugin config
  - print-site:
      add_to_navigation: false
      print_page_title: 'Stampa'
      add_table_of_contents: false
      toc_title: 'Indice dei contenuti'
      toc_depth: 6
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true

nav:
- "<span class='ms-Icon ms-Icon--SecondaryNav'></span> Shared Features": developers.md
- "<span class='ms-Icon ms-Icon--ViewDashboard'></span> Amministrazione": Administration.md
- "<span class='ms-Icon ms-Icon--AddToShoppingList'></span> PDF": SCMP_SUM_it.pdf


markdown_extensions:
  - markdown_captions
  - admonition
  - pymdownx.details
  - pymdownx.superfences